make task1: Task_1.s print_ram.c
	rm -vf task1
	gcc -no-pie Task_1.s print_ram.c -o task1
	./task1

make task2: Task_2.s print_ram.c
	rm -vf task2
	gcc -no-pie Task_2.s print_ram.c -o task2
	./task2

make task3: Task_3.s print_ram.c
	rm -vf task3
	gcc -no-pie Task_3.s print_ram.c -o task3
	./task3

make task4: Task_4.s print_ram.c
	rm -vf task4
	gcc -no-pie Task_4.s print_ram.c -o task4
	./task4
	